blank_issues_enabled: false
contact_links:
  - name: 🆕 Create new issue
    url: http://new-issue.ant.design?repo=ant-design-mobile-rn
    about: The issue which is not created via http://new-issue.ant.design will be closed immediately.
  - name: 🐛 创建一个错误报告issue
    url: https://github.com/ant-design/ant-design-mobile-rn/issues/new?assignees=1uokun&labels=Bug🐛&template=bug_report.yml&title=%5BBUG%5D
    about: 不使用模版创建的issue可能会被机器人自动关闭。