blank_issues_enabled: false
contact_links:
  - name: 🆕 Create new issue
    url: https://github.com/ant-design/ant-design-mobile-rn/issues/new?expand=1&template=ISSUE_TEMPLATE.md
    about: A good question can help us quickly locate the problem for you.
  - name: 🆕 创建一个新 Issue
    url: http://new-issue.ant.design?repo=ant-design-mobile-rn
    about: 通过模版可以快速创建issue，并且能够帮助我们更快定位问题。